# Generated by Django 6.0.2 on 2026-10-02 09:47

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='dimensions',
            field=models.CharField(blank=True, help_text='For charts or print size, e.g. A1, A2, 8.5x11', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='isbn_or_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_language',
            field=models.CharField(default='English', help_text='e.g. English, French', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_language',
            field=models.CharField(blank=True, help_text='Target language for bilingual projects, e.g. French', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='target_age_group',
            field=models.CharField(blank=True, help_text='e.g. Ages 3-5, Grades 1-3', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('digital', 'Digital Projects'), ('language', 'Language Projects'), ('chart', 'Charts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('english_storybook', 'English Storybook'), ('french_storybook', 'French Storybook'), ('digital_storybook', 'Storybook (General)'), ('bilingual_reader', 'Bilingual Reader'), ('bilingual_vocabulary', 'Bilingual Vocabulary Book'), ('alphabet_chart', 'Alphabet Chart'), ('syllable_chart', 'Syllable Chart')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea / Concept'), ('drafting', 'Manuscript Drafting'), ('translation', 'Translating'), ('illustration', 'Illustration / Graphic Design'), ('editorial_review', 'Editorial Review & Proofreading'), ('layout_approval', 'Layout & Pre-Press Approval'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=50),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. English Draft, French Translation, Illustrations Complete', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('manuscript', 'Manuscript (Doc/Text)'), ('illustration', 'Illustration / Graphic'), ('cover_art', 'Cover Art'), ('chart_grid', 'Chart Grid / Vector'), ('proof_pdf', 'Proof PDF'), ('final_export', 'Final Print / Digital Export'), ('other', 'Other Asset')], default='manuscript', max_length=50)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('file_url', models.URLField(blank=True, help_text='Direct link or external document link (e.g. Google Docs/Drive)')),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('co_author', 'Co-Author'), ('translator', 'Translator'), ('illustrator', 'Illustrator'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('typesetter', 'Typesetter / Layout Artist'), ('project_manager', 'Project Manager')], max_length=50)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('deliverable_notes', models.TextField(blank=True, help_text='Instructions, milestones, or scope for this contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', through='projects.ProjectAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
