[project]
name = "open-mind-publishing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cloudinary>=1.46.2",
    "cryptography>=50.0.2",
    "dj-database-url>=3.1.2",
    "django>=6.1.1",
    "django-allauth>=65.19.5",
    "django-cloudinary-storage>=0.3.0",
    "django-cors-headers>=4.9.0",
    "django-ninja>=1.7.1",
    "email-validator>=2.3.0",
    "gunicorn>=26.2.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "psycopg>=3.3.6",
    "pyjwt>=2.15.1",
    "python-decouple>=3.8",
    "whitenoise>=6.12.0",
]
