# Generated by Django 6.0.2 on 2026-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('author', 'Author'), ('freelancer', 'Freelancer'), ('illustrator', 'Illustrator'), ('translator', 'Translator'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('project_manager', 'Project Manager')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_or_agent_contact',
            field=models.CharField(blank=True, help_text='Agent, manager, or emergency contact info', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pen_name',
            field=models.CharField(blank=True, help_text='Public pen name or publishing alias', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialties_or_languages',
            field=models.CharField(blank=True, help_text="e.g. 'English to French Translation', 'Watercolor Storybook Art', 'Phonetics'", max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
    ]
