"""
Django settings for open_mind_publishing project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    "open-mind-publishing.onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    #image storage
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    #allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.headless',

    #cors api
    'corsheaders',

    #apps
    'accounts',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'open_mind_publishing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'open_mind_publishing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 2. Automatically override if a DATABASE_URL environment variable is provided (Production)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL and not DEBUG:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=True
    )
    # Essential for Neon serverless: keeps active validation checks
    # so connections don't drop when your database scales down to zero
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True

#**leave database_url out of local env, only add it in the live servers env like render

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators


# Tell allauth headless exactly where to look for the native JWT handler class
ALLAUTH_HEADLESS_TOKEN_STRATEGY = "allauth.headless.tokens.jwt.JWTTokenStrategy"


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Add django-allauth's specific backend for checking credentials
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Keeps your Django admin working
    'allauth.account.auth_backends.AuthenticationBackend', # Required for allauth
]

# Updated for newer django-allauth packages
ACCOUNT_LOGIN_METHODS = {'email', 'username'}



# Replaces old account field requirement settings clean
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

ACCOUNT_UNIQUE_EMAIL = True           

AUTH_USER_MODEL = 'accounts.CustomUser'

# Tell allauth to use JWT tokens instead of browser session cookies (headless mode)
HEADLESS_TOKEN_STRATEGY = "allauth.headless.tokens.strategies.jwt.strategy.JWTTokenStrategy"

# Use HS256 (HMAC-SHA256) so allauth signs JWTs with Django's SECRET_KEY.
# RS256 (the default) requires a separate RSA private key file — use that in production.
HEADLESS_JWT_ALGORITHM = "HS256"

if not DEBUG:
    FRONTEND_BASE_URL =  "https://open-mind-publishing-frontend.vercel.app/"
else:
    FRONTEND_BASE_URL = "http://localhost:5173"

# The routes your frontend app uses to catch email verifies or password resets
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_BASE_URL}/verify-email/{{key}}",
    "account_reset_password_from_key": f"{FRONTEND_BASE_URL}/password/reset/{{key}}",
    "account_signup": f"{FRONTEND_BASE_URL}/signup",
}

#cors api
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://open-mind-publishing-frontend.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = False #not all urls can access this backend

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-session-token"
)

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# cloudinary settings
# use dictionary to avoid circular imports in the produce app - which has settings import and cloudinary

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

# 2. Explicit fallback initialization for the lower-level uploader pipeline = cloudinary storage could not read image upload
cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET'),
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'


APPEND_SLASH = True